package com.laos.hiramoto.ilovelaos.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "DICTIONARY".
 */
@Entity
public class Dictionary {

    @Id
    private long _id;
    /** Not-null value. */
    private String yomi;
    /** Not-null value. */
    private String wordJpn;
    /** Not-null value. */
    private String wordLao;
    /** Not-null value. */
    private String typeLaoScript;
    @Generated(hash = 1381135246)
    public Dictionary(long _id, String yomi, String wordJpn, String wordLao, String typeLaoScript) {
        this._id = _id;
        this.yomi = yomi;
        this.wordJpn = wordJpn;
        this.wordLao = wordLao;
        this.typeLaoScript = typeLaoScript;
    }
    @Generated(hash = 487998537)
    public Dictionary() {
    }
    public long get_id() {
        return this._id;
    }
    public void set_id(long _id) {
        this._id = _id;
    }
    public String getYomi() {
        return this.yomi;
    }
    public void setYomi(String yomi) {
        this.yomi = yomi;
    }
    public String getWordJpn() {
        return this.wordJpn;
    }
    public void setWordJpn(String wordJpn) {
        this.wordJpn = wordJpn;
    }
    public String getWordLao() {
        return this.wordLao;
    }
    public void setWordLao(String wordLao) {
        this.wordLao = wordLao;
    }
    public String getTypeLaoScript() {
        return this.typeLaoScript;
    }
    public void setTypeLaoScript(String typeLaoScript) {
        this.typeLaoScript = typeLaoScript;
    }

}
