package com.laos.hiramoto.ilovelaos.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table "WORDS".
 */
@Entity
public class Word {

    @Id
    private long _id;
    private String laotian;
    private String kana;
    private String japanese;
    private String roman;
    private String situation;
    private Integer lesson;
    @Generated(hash = 1577890071)
    public Word(long _id, String laotian, String kana, String japanese, String roman, String situation,
            Integer lesson) {
        this._id = _id;
        this.laotian = laotian;
        this.kana = kana;
        this.japanese = japanese;
        this.roman = roman;
        this.situation = situation;
        this.lesson = lesson;
    }
    @Generated(hash = 3342184)
    public Word() {
    }
    public long get_id() {
        return this._id;
    }
    public void set_id(long _id) {
        this._id = _id;
    }
    public String getLaotian() {
        return this.laotian;
    }
    public void setLaotian(String laotian) {
        this.laotian = laotian;
    }
    public String getKana() {
        return this.kana;
    }
    public void setKana(String kana) {
        this.kana = kana;
    }
    public String getJapanese() {
        return this.japanese;
    }
    public void setJapanese(String japanese) {
        this.japanese = japanese;
    }
    public String getRoman() {
        return this.roman;
    }
    public void setRoman(String roman) {
        this.roman = roman;
    }
    public String getSituation() {
        return this.situation;
    }
    public void setSituation(String situation) {
        this.situation = situation;
    }
    public Integer getLesson() {
        return this.lesson;
    }
    public void setLesson(Integer lesson) {
        this.lesson = lesson;
    }

}
